#! /bin/sh

### BEGIN INIT INFO
# Provides:          myip
# Required-Start:    $network $ssh
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Send wan-ip to email
# Description: Send wan-ip to email
### END INIT INFO

M=/etc/init.d/myip
ROOT_DIR=/home/pi/init

set -e

case "$1" in
  start)
	echo "myip is starting ..."
	${ROOT_DIR}/myip.sh
	echo "myip is started successfully"
	;;
  stop)
	echo "myip is stopping ..."
	echo "myip is stopped successfully"
	;;
  *)
	echo "Usage: $N {start|stop}" >&2
	exit 1
	;;
esac

exit 0
