#!/bin/sh
### BEGIN INIT INFO
# Provides: mymotion
# Required-Start: networking sshd
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: Start motion with customized config file
# Description: Start motion with customized configuration
### END INIT INFO

M=/etc/init.d/mymotion
CONF_FILE=/home/pi/motion/motion.conf

case "$1" in
  start)
	echo "mymotion is starting ..."
	sudo motion -c $CONF_FILE > /home/pi/mymotion.log &
	echo "mymotion is started successfully"
	;;
  stop)
	echo "mymotion is stopping ..."
	sudo killall motion
	echo "mymotion is stopped successfully"
	;;
  *)
	echo "Usage: $N {start|stop}" >&2
	exit 1
	;;

esac

exit 0
